// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-axios";
import type {
  AuthJwtLoginData,
  AuthJwtLoginError,
  AuthJwtLoginResponse,
  AuthJwtLogoutError,
  AuthJwtLogoutResponse,
  RegisterRegisterData,
  RegisterRegisterError,
  RegisterRegisterResponse,
  ResetForgotPasswordData,
  ResetForgotPasswordError,
  ResetForgotPasswordResponse,
  ResetResetPasswordData,
  ResetResetPasswordError,
  ResetResetPasswordResponse,
  VerifyRequestTokenData,
  VerifyRequestTokenError,
  VerifyRequestTokenResponse,
  VerifyVerifyData,
  VerifyVerifyError,
  VerifyVerifyResponse,
  UsersCurrentUserError,
  UsersCurrentUserResponse,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserError,
  UsersPatchCurrentUserResponse,
  UsersUserData,
  UsersUserError,
  UsersUserResponse,
  UsersPatchUserData,
  UsersPatchUserError,
  UsersPatchUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserError,
  UsersDeleteUserResponse,
  ReadItemData,
  ReadItemError,
  ReadItemResponse,
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  CreateControlData,
  CreateControlError,
  CreateControlResponse,
  ReadControlsData,
  ReadControlsError,
  ReadControlsResponse,
  ReadControlData,
  ReadControlError,
  ReadControlResponse,
  UpdateControlData,
  UpdateControlError,
  UpdateControlResponse,
  DeleteControlData,
  DeleteControlError,
  DeleteControlResponse,
  CreateRiskData,
  CreateRiskError,
  CreateRiskResponse,
  ReadRisksData,
  ReadRisksError,
  ReadRisksResponse,
  ReadRiskData,
  ReadRiskError,
  ReadRiskResponse,
  UpdateRiskData,
  UpdateRiskError,
  UpdateRiskResponse,
  DeleteRiskData,
  DeleteRiskError,
  DeleteRiskResponse,
  CreateBusinessProcessData,
  CreateBusinessProcessError,
  CreateBusinessProcessResponse,
  ReadBusinessProcessesData,
  ReadBusinessProcessesError,
  ReadBusinessProcessesResponse,
  ReadBusinessProcessData,
  ReadBusinessProcessError,
  ReadBusinessProcessResponse,
  UpdateBusinessProcessData,
  UpdateBusinessProcessError,
  UpdateBusinessProcessResponse,
  DeleteBusinessProcessData,
  DeleteBusinessProcessError,
  DeleteBusinessProcessResponse,
  CreateRegulatoryFrameworkData,
  CreateRegulatoryFrameworkError,
  CreateRegulatoryFrameworkResponse,
  ReadRegulatoryFrameworksData,
  ReadRegulatoryFrameworksError,
  ReadRegulatoryFrameworksResponse,
  ReadRegulatoryFrameworkData,
  ReadRegulatoryFrameworkError,
  ReadRegulatoryFrameworkResponse,
  UpdateRegulatoryFrameworkData,
  UpdateRegulatoryFrameworkError,
  UpdateRegulatoryFrameworkResponse,
  DeleteRegulatoryFrameworkData,
  DeleteRegulatoryFrameworkError,
  DeleteRegulatoryFrameworkResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  ListUsersData,
  ListUsersError,
  ListUsersResponse,
  GetCurrentUserError,
  GetCurrentUserResponse,
  UpdateUserRoleData,
  UpdateUserRoleError,
  UpdateUserRoleResponse,
  UploadDocumentData,
  UploadDocumentError,
  UploadDocumentResponse,
  ListDocumentsError,
  ListDocumentsResponse,
  GetDocumentData,
  GetDocumentError,
  GetDocumentResponse,
  DeleteDocumentData,
  DeleteDocumentError,
  DeleteDocumentResponse,
  RenameDocumentData,
  RenameDocumentError,
  RenameDocumentResponse,
  ManuallyProcessDocumentData,
  ManuallyProcessDocumentError,
  ManuallyProcessDocumentResponse,
  ListSuggestionsData,
  ListSuggestionsError,
  ListSuggestionsResponse,
  UpdateSuggestionStatusData,
  UpdateSuggestionStatusError,
  UpdateSuggestionStatusResponse,
  ListAuditLogsData,
  ListAuditLogsError,
  ListAuditLogsResponse,
  GetDashboardMetricsError,
  GetDashboardMetricsResponse,
  GetPendingReviewsData,
  GetPendingReviewsError,
  GetPendingReviewsResponse,
  GetSuggestionDetailData,
  GetSuggestionDetailError,
  GetSuggestionDetailResponse,
  SubmitAssessmentData,
  SubmitAssessmentError,
  SubmitAssessmentResponse,
  CreateMappingData,
  CreateMappingError,
  CreateMappingResponse,
  DeleteMappingData,
  DeleteMappingError,
  DeleteMappingResponse,
  GetMappingsForControlData,
  GetMappingsForControlError,
  GetMappingsForControlResponse,
  GetMappingsForRequirementData,
  GetMappingsForRequirementError,
  GetMappingsForRequirementResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLoginResponse,
    AuthJwtLoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/jwt/login",
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponse,
    AuthJwtLogoutError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/jwt/logout",
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RegisterRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterRegisterResponse,
    RegisterRegisterError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/register",
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetForgotPasswordResponse,
    ResetForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/forgot-password",
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetResetPasswordResponse,
    ResetResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/reset-password",
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyRequestTokenResponse,
    VerifyRequestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/request-verify-token",
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyVerifyResponse,
    VerifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/verify",
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponse,
    UsersCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchCurrentUserResponse,
    UsersPatchCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUserResponse,
    UsersUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchUserResponse,
    UsersPatchUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserResponse,
    UsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponse,
    ReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateItemResponse,
    CreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteItemResponse,
    DeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Create Control
 */
export const createControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateControlResponse,
    CreateControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls",
  });
};

/**
 * Read Controls
 */
export const readControls = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadControlsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadControlsResponse,
    ReadControlsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls",
  });
};

/**
 * Read Control
 */
export const readControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ReadControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadControlResponse,
    ReadControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Update Control
 */
export const updateControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateControlResponse,
    UpdateControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Delete Control
 */
export const deleteControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteControlResponse,
    DeleteControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Create Risk
 */
export const createRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRiskResponse,
    CreateRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks",
  });
};

/**
 * Read Risks
 */
export const readRisks = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadRisksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRisksResponse,
    ReadRisksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks",
  });
};

/**
 * Read Risk
 */
export const readRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ReadRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRiskResponse,
    ReadRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Update Risk
 */
export const updateRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateRiskResponse,
    UpdateRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Delete Risk
 */
export const deleteRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRiskResponse,
    DeleteRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Create Business Process
 */
export const createBusinessProcess = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateBusinessProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateBusinessProcessResponse,
    CreateBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes",
  });
};

/**
 * Read Business Processes
 */
export const readBusinessProcesses = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadBusinessProcessesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadBusinessProcessesResponse,
    ReadBusinessProcessesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes",
  });
};

/**
 * Read Business Process
 */
export const readBusinessProcess = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ReadBusinessProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadBusinessProcessResponse,
    ReadBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Update Business Process
 */
export const updateBusinessProcess = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateBusinessProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateBusinessProcessResponse,
    UpdateBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Delete Business Process
 */
export const deleteBusinessProcess = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteBusinessProcessData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteBusinessProcessResponse,
    DeleteBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Create Regulatory Framework
 */
export const createRegulatoryFramework = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateRegulatoryFrameworkData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRegulatoryFrameworkResponse,
    CreateRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks",
  });
};

/**
 * Read Regulatory Frameworks
 */
export const readRegulatoryFrameworks = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ReadRegulatoryFrameworksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRegulatoryFrameworksResponse,
    ReadRegulatoryFrameworksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks",
  });
};

/**
 * Read Regulatory Framework
 */
export const readRegulatoryFramework = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ReadRegulatoryFrameworkData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRegulatoryFrameworkResponse,
    ReadRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Update Regulatory Framework
 */
export const updateRegulatoryFramework = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateRegulatoryFrameworkData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateRegulatoryFrameworkResponse,
    UpdateRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Delete Regulatory Framework
 */
export const deleteRegulatoryFramework = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteRegulatoryFrameworkData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRegulatoryFrameworkResponse,
    DeleteRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Create User
 * Create a new user.
 * Requires admin role.
 * The new user is assigned to the admin's tenant.
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateUserResponse,
    CreateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users",
  });
};

/**
 * List Users
 * List users in the current tenant, optionally filtered by role.
 * Requires admin or compliance_officer role.
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListUsersResponse,
    ListUsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users",
  });
};

/**
 * Get Current User
 * Get the current authenticated user's information including their role.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentUserResponse,
    GetCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update User Role
 */
export const updateUserRole = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateUserRoleData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateUserRoleResponse,
    UpdateUserRoleError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}/role",
  });
};

/**
 * Upload Document
 * Upload a regulatory document for AI analysis.
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadDocumentResponse,
    UploadDocumentError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/documents/upload",
  });
};

/**
 * List Documents
 * List all documents for the current user's tenant.
 */
export const listDocuments = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListDocumentsResponse,
    ListDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents",
  });
};

/**
 * Get Document
 * Get a specific document by ID.
 *
 * - Requires admin, bpo, or executive role
 * - Returns document metadata
 */
export const getDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetDocumentResponse,
    GetDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}",
  });
};

/**
 * Delete Document
 * Archive a document (soft delete).
 *
 * - **document_id**: UUID of the document to archive
 * - Requires admin role
 * - Moves document to archive in both database and Supabase storage
 * - Returns success message
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteDocumentResponse,
    DeleteDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}",
  });
};

/**
 * Rename Document
 * Rename a document.
 *
 * - **document_id**: UUID of the document to rename
 * - **new_filename**: New filename for the document (in request body)
 * - Requires admin role
 * - Updates filename in database only (storage path remains unchanged)
 * - File extension is preserved automatically
 * - Returns updated document metadata
 */
export const renameDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RenameDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    RenameDocumentResponse,
    RenameDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/rename",
  });
};

/**
 * Manually Process Document
 * Manually trigger document processing (for testing/debugging).
 *
 * - **document_id**: UUID of the document to process
 * - Requires admin role
 * - Processes document synchronously and returns detailed status
 * - Useful for debugging when automatic processing fails
 */
export const manuallyProcessDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ManuallyProcessDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ManuallyProcessDocumentResponse,
    ManuallyProcessDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/process",
  });
};

/**
 * List Suggestions
 * List AI suggestions with optional status filtering.
 * Filtered by tenant - only shows suggestions from documents uploaded by users in the same tenant.
 */
export const listSuggestions = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListSuggestionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSuggestionsResponse,
    ListSuggestionsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/suggestions",
  });
};

/**
 * Update Suggestion Status
 * Update the status of an AI suggestion.
 * Transitions:
 * - pending -> awaiting_bpo_approval (Accept)
 * - pending -> rejected (Reject)
 */
export const updateSuggestionStatus = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateSuggestionStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateSuggestionStatusResponse,
    UpdateSuggestionStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/suggestions/{suggestion_id}/status",
  });
};

/**
 * List Audit Logs
 * Retrieve audit logs.
 * Requires admin or compliance_officer role.
 */
export const listAuditLogs = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ListAuditLogsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAuditLogsResponse,
    ListAuditLogsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/audit-logs",
  });
};

/**
 * Get Dashboard Metrics
 * Retrieve role-specific dashboard metrics for the authenticated user.
 *
 * Returns:
 * DashboardMetrics: Role-specific dashboard cards and data
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (user inactive or invalid tenant)
 * 500: Internal server error (database/service failure)
 */
export const getDashboardMetrics = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetDashboardMetricsResponse,
    GetDashboardMetricsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/dashboard/metrics",
  });
};

/**
 * Get Pending Reviews
 * Retrieve paginated list of suggestions with status 'pending_review' assigned to the logged-in BPO.
 *
 * Only accessible to users with BPO role. Returns suggestions filtered by:
 * - status = "pending_review"
 * - assigned_bpo_id = current_user.id
 * - tenant_id = current_user.tenant_id (enforced by RLS)
 *
 * Args:
 * page: Page number (1-indexed)
 * size: Number of items per page (max 100)
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * PendingReviewsResponse: Paginated list of pending review items
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-BPO user or user has no tenant)
 * 500: Internal server error
 */
export const getPendingReviews = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<GetPendingReviewsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPendingReviewsResponse,
    GetPendingReviewsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/pending",
  });
};

/**
 * Get Suggestion Detail
 * Retrieve detailed information for a specific AI suggestion.
 *
 * Only accessible to BPO assigned to the suggestion.
 *
 * Args:
 * suggestion_id: ID of the suggestion
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * SuggestionDetailResponse: Detailed suggestion data
 *
 * Raises:
 * 403: Forbidden (not BPO or not assigned)
 * 404: Not Found
 */
export const getSuggestionDetail = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetSuggestionDetailData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSuggestionDetailResponse,
    GetSuggestionDetailError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/{suggestion_id}",
  });
};

/**
 * Submit Assessment
 * Submit BPO assessment action (approve or discard) for an AI suggestion.
 *
 * Authorization checks:
 * - User must have BPO role
 * - Suggestion.assigned_bpo_id must match current_user.id
 * - Suggestion.tenant_id must match current_user.tenant_id (enforced by service layer)
 *
 * Validation:
 * - For approve action: residual_risk is REQUIRED (400 Bad Request if missing)
 * - Suggestion must exist and have status "pending_review" (404 if not found, 409 if wrong status)
 *
 * Side effects:
 * - Approve: Creates active records (business_process, risk, control), updates status to "active"
 * - Discard: Updates status to "archived"
 * - Both actions: Creates immutable audit log entry
 *
 * Args:
 * suggestion_id: ID of the suggestion to assess
 * request: AssessmentRequest with action, residual_risk (if approve), and optional edits
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * AssessmentResponse: Success status, message, updated status, audit_log_id, and active_record_ids (if approved)
 *
 * Raises:
 * 400: Bad Request (residual_risk missing for approve action)
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-BPO user, not assigned to this suggestion, or no tenant)
 * 404: Not Found (suggestion doesn't exist or belongs to different tenant)
 * 409: Conflict (suggestion status is not "pending_review")
 * 500: Internal server error
 */
export const submitAssessment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SubmitAssessmentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SubmitAssessmentResponse,
    SubmitAssessmentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/{suggestion_id}/assess",
  });
};

/**
 * Create Mapping
 * Create a new control-to-requirement mapping.
 *
 * Only accessible to Admin users. Validates that both control and requirement
 * exist in the user's tenant, prevents duplicate mappings, and logs the action
 * to the audit trail.
 *
 * Args:
 * payload: MappingCreate with control_id and regulatory_requirement_id
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingDetail: Created mapping with control and requirement names
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin user)
 * 400: Bad Request (invalid control_id or requirement_id)
 * 409: Conflict (mapping already exists)
 */
export const createMapping = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateMappingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateMappingResponse,
    CreateMappingError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings",
  });
};

/**
 * Delete Mapping
 * Delete a control-to-requirement mapping.
 *
 * Only accessible to Admin users. Idempotent operation - returns 404 if
 * mapping doesn't exist. Logs the deletion to the audit trail.
 *
 * Args:
 * payload: MappingDelete with control_id and regulatory_requirement_id
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin user)
 * 404: Not Found (mapping doesn't exist)
 */
export const deleteMapping = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteMappingData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteMappingResponse,
    DeleteMappingError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings",
  });
};

/**
 * Get Mappings For Control
 * Get all regulatory requirements mapped to a specific control.
 *
 * Accessible to Admin, Executive, and BPO users. Returns list of mappings
 * with requirement names for display.
 *
 * Args:
 * control_id: UUID of the control
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingListResponse: List of mappings with total count
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin/Executive/BPO user)
 * 404: Not Found (control doesn't exist or not in user's tenant)
 */
export const getMappingsForControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetMappingsForControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMappingsForControlResponse,
    GetMappingsForControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings/control/{control_id}",
  });
};

/**
 * Get Mappings For Requirement
 * Get all controls mapped to a specific regulatory requirement.
 *
 * Accessible to Admin, Executive, and BPO users. Returns list of mappings
 * with control names for display.
 *
 * Args:
 * requirement_id: UUID of the regulatory requirement
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingListResponse: List of mappings with total count
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin/Executive/BPO user)
 * 404: Not Found (requirement doesn't exist or not in user's tenant)
 */
export const getMappingsForRequirement = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetMappingsForRequirementData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetMappingsForRequirementResponse,
    GetMappingsForRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings/requirement/{requirement_id}",
  });
};
