// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-axios";
import type {
  AuthAuthJwtLoginData,
  AuthAuthJwtLoginError,
  AuthAuthJwtLoginResponse,
  AuthAuthJwtLogoutError,
  AuthAuthJwtLogoutResponse,
  AuthRegisterRegisterData,
  AuthRegisterRegisterError,
  AuthRegisterRegisterResponse,
  AuthResetForgotPasswordData,
  AuthResetForgotPasswordError,
  AuthResetForgotPasswordResponse,
  AuthResetResetPasswordData,
  AuthResetResetPasswordError,
  AuthResetResetPasswordResponse,
  AuthVerifyRequestTokenData,
  AuthVerifyRequestTokenError,
  AuthVerifyRequestTokenResponse,
  AuthVerifyVerifyData,
  AuthVerifyVerifyError,
  AuthVerifyVerifyResponse,
  UsersUsersCurrentUserError,
  UsersUsersCurrentUserResponse,
  UsersUsersPatchCurrentUserData,
  UsersUsersPatchCurrentUserError,
  UsersUsersPatchCurrentUserResponse,
  UsersUsersUserData,
  UsersUsersUserError,
  UsersUsersUserResponse,
  UsersUsersPatchUserData,
  UsersUsersPatchUserError,
  UsersUsersPatchUserResponse,
  UsersUsersDeleteUserData,
  UsersUsersDeleteUserError,
  UsersUsersDeleteUserResponse,
  ItemReadItemData,
  ItemReadItemError,
  ItemReadItemResponse,
  ItemCreateItemData,
  ItemCreateItemError,
  ItemCreateItemResponse,
  ItemDeleteItemData,
  ItemDeleteItemError,
  ItemDeleteItemResponse,
  ControlsCreateControlData,
  ControlsCreateControlError,
  ControlsCreateControlResponse,
  ControlsReadControlsData,
  ControlsReadControlsError,
  ControlsReadControlsResponse,
  ControlsReadControlData,
  ControlsReadControlError,
  ControlsReadControlResponse,
  ControlsUpdateControlData,
  ControlsUpdateControlError,
  ControlsUpdateControlResponse,
  ControlsDeleteControlData,
  ControlsDeleteControlError,
  ControlsDeleteControlResponse,
  RisksCreateRiskData,
  RisksCreateRiskError,
  RisksCreateRiskResponse,
  RisksReadRisksData,
  RisksReadRisksError,
  RisksReadRisksResponse,
  RisksReadRiskData,
  RisksReadRiskError,
  RisksReadRiskResponse,
  RisksUpdateRiskData,
  RisksUpdateRiskError,
  RisksUpdateRiskResponse,
  RisksDeleteRiskData,
  RisksDeleteRiskError,
  RisksDeleteRiskResponse,
  BusinessProcessesCreateBusinessProcessData,
  BusinessProcessesCreateBusinessProcessError,
  BusinessProcessesCreateBusinessProcessResponse,
  BusinessProcessesReadBusinessProcessesData,
  BusinessProcessesReadBusinessProcessesError,
  BusinessProcessesReadBusinessProcessesResponse,
  BusinessProcessesReadBusinessProcessData,
  BusinessProcessesReadBusinessProcessError,
  BusinessProcessesReadBusinessProcessResponse,
  BusinessProcessesUpdateBusinessProcessData,
  BusinessProcessesUpdateBusinessProcessError,
  BusinessProcessesUpdateBusinessProcessResponse,
  BusinessProcessesDeleteBusinessProcessData,
  BusinessProcessesDeleteBusinessProcessError,
  BusinessProcessesDeleteBusinessProcessResponse,
  RegulatoryFrameworksCreateRegulatoryFrameworkData,
  RegulatoryFrameworksCreateRegulatoryFrameworkError,
  RegulatoryFrameworksCreateRegulatoryFrameworkResponse,
  RegulatoryFrameworksReadRegulatoryFrameworksData,
  RegulatoryFrameworksReadRegulatoryFrameworksError,
  RegulatoryFrameworksReadRegulatoryFrameworksResponse,
  RegulatoryFrameworksReadRegulatoryFrameworkData,
  RegulatoryFrameworksReadRegulatoryFrameworkError,
  RegulatoryFrameworksReadRegulatoryFrameworkResponse,
  RegulatoryFrameworksUpdateRegulatoryFrameworkData,
  RegulatoryFrameworksUpdateRegulatoryFrameworkError,
  RegulatoryFrameworksUpdateRegulatoryFrameworkResponse,
  RegulatoryFrameworksDeleteRegulatoryFrameworkData,
  RegulatoryFrameworksDeleteRegulatoryFrameworkError,
  RegulatoryFrameworksDeleteRegulatoryFrameworkResponse,
  RegulatoryRequirementsCreateRegulatoryRequirementData,
  RegulatoryRequirementsCreateRegulatoryRequirementError,
  RegulatoryRequirementsCreateRegulatoryRequirementResponse,
  RegulatoryRequirementsReadRegulatoryRequirementsData,
  RegulatoryRequirementsReadRegulatoryRequirementsError,
  RegulatoryRequirementsReadRegulatoryRequirementsResponse,
  RegulatoryRequirementsReadRegulatoryRequirementData,
  RegulatoryRequirementsReadRegulatoryRequirementError,
  RegulatoryRequirementsReadRegulatoryRequirementResponse,
  RegulatoryRequirementsUpdateRegulatoryRequirementData,
  RegulatoryRequirementsUpdateRegulatoryRequirementError,
  RegulatoryRequirementsUpdateRegulatoryRequirementResponse,
  RegulatoryRequirementsDeleteRegulatoryRequirementData,
  RegulatoryRequirementsDeleteRegulatoryRequirementError,
  RegulatoryRequirementsDeleteRegulatoryRequirementResponse,
  UsersCreateUserData,
  UsersCreateUserError,
  UsersCreateUserResponse,
  UsersListUsersData,
  UsersListUsersError,
  UsersListUsersResponse,
  UsersGetCurrentUserError,
  UsersGetCurrentUserResponse,
  UsersUpdateUserRoleData,
  UsersUpdateUserRoleError,
  UsersUpdateUserRoleResponse,
  DocumentsUploadDocumentData,
  DocumentsUploadDocumentError,
  DocumentsUploadDocumentResponse,
  DocumentsListDocumentsError,
  DocumentsListDocumentsResponse,
  DocumentsGetDocumentData,
  DocumentsGetDocumentError,
  DocumentsGetDocumentResponse,
  DocumentsDeleteDocumentData,
  DocumentsDeleteDocumentError,
  DocumentsDeleteDocumentResponse,
  DocumentsRenameDocumentData,
  DocumentsRenameDocumentError,
  DocumentsRenameDocumentResponse,
  DocumentsManuallyProcessDocumentData,
  DocumentsManuallyProcessDocumentError,
  DocumentsManuallyProcessDocumentResponse,
  SuggestionsListSuggestionsData,
  SuggestionsListSuggestionsError,
  SuggestionsListSuggestionsResponse,
  SuggestionsUpdateSuggestionStatusData,
  SuggestionsUpdateSuggestionStatusError,
  SuggestionsUpdateSuggestionStatusResponse,
  AuditLogsListAuditLogsData,
  AuditLogsListAuditLogsError,
  AuditLogsListAuditLogsResponse,
  DashboardGetDashboardMetricsError,
  DashboardGetDashboardMetricsResponse,
  AssessmentsGetPendingReviewsData,
  AssessmentsGetPendingReviewsError,
  AssessmentsGetPendingReviewsResponse,
  AssessmentsGetSuggestionDetailData,
  AssessmentsGetSuggestionDetailError,
  AssessmentsGetSuggestionDetailResponse,
  AssessmentsSubmitAssessmentData,
  AssessmentsSubmitAssessmentError,
  AssessmentsSubmitAssessmentResponse,
  MappingsCreateMappingData,
  MappingsCreateMappingError,
  MappingsCreateMappingResponse,
  MappingsDeleteMappingData,
  MappingsDeleteMappingError,
  MappingsDeleteMappingResponse,
  MappingsGetMappingsForControlData,
  MappingsGetMappingsForControlError,
  MappingsGetMappingsForControlResponse,
  MappingsGetMappingsForRequirementData,
  MappingsGetMappingsForRequirementError,
  MappingsGetMappingsForRequirementResponse,
  ReportsGenerateGapAnalysisReportData,
  ReportsGenerateGapAnalysisReportError,
  ReportsGenerateGapAnalysisReportResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authAuthJwtLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthAuthJwtLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthAuthJwtLoginResponse,
    AuthAuthJwtLoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/jwt/login",
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authAuthJwtLogout = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthAuthJwtLogoutResponse,
    AuthAuthJwtLogoutError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/jwt/logout",
  });
};

/**
 * Register:Register
 */
export const authRegisterRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthRegisterRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthRegisterRegisterResponse,
    AuthRegisterRegisterError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/register",
  });
};

/**
 * Reset:Forgot Password
 */
export const authResetForgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthResetForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthResetForgotPasswordResponse,
    AuthResetForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/forgot-password",
  });
};

/**
 * Reset:Reset Password
 */
export const authResetResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthResetResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthResetResetPasswordResponse,
    AuthResetResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/reset-password",
  });
};

/**
 * Verify:Request-Token
 */
export const authVerifyRequestToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthVerifyRequestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthVerifyRequestTokenResponse,
    AuthVerifyRequestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/request-verify-token",
  });
};

/**
 * Verify:Verify
 */
export const authVerifyVerify = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthVerifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthVerifyVerifyResponse,
    AuthVerifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/verify",
  });
};

/**
 * Users:Current User
 */
export const usersUsersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUsersCurrentUserResponse,
    UsersUsersCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:Patch Current User
 */
export const usersUsersPatchCurrentUser = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<UsersUsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersUsersPatchCurrentUserResponse,
    UsersUsersPatchCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:User
 */
export const usersUsersUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUsersUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUsersUserResponse,
    UsersUsersUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Patch User
 */
export const usersUsersPatchUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUsersPatchUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersUsersPatchUserResponse,
    UsersUsersPatchUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Delete User
 */
export const usersUsersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersUsersDeleteUserResponse,
    UsersUsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Read Item
 */
export const itemReadItem = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ItemReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ItemReadItemResponse,
    ItemReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Create Item
 */
export const itemCreateItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemCreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ItemCreateItemResponse,
    ItemCreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Delete Item
 */
export const itemDeleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ItemDeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ItemDeleteItemResponse,
    ItemDeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Create Control
 */
export const controlsCreateControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ControlsCreateControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ControlsCreateControlResponse,
    ControlsCreateControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls",
  });
};

/**
 * Read Controls
 */
export const controlsReadControls = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<ControlsReadControlsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ControlsReadControlsResponse,
    ControlsReadControlsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls",
  });
};

/**
 * Read Control
 */
export const controlsReadControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ControlsReadControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ControlsReadControlResponse,
    ControlsReadControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Update Control
 */
export const controlsUpdateControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ControlsUpdateControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    ControlsUpdateControlResponse,
    ControlsUpdateControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Delete Control
 */
export const controlsDeleteControl = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ControlsDeleteControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ControlsDeleteControlResponse,
    ControlsDeleteControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/controls/{control_id}",
  });
};

/**
 * Create Risk
 */
export const risksCreateRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RisksCreateRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RisksCreateRiskResponse,
    RisksCreateRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks",
  });
};

/**
 * Read Risks
 */
export const risksReadRisks = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<RisksReadRisksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RisksReadRisksResponse,
    RisksReadRisksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks",
  });
};

/**
 * Read Risk
 */
export const risksReadRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RisksReadRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RisksReadRiskResponse,
    RisksReadRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Update Risk
 */
export const risksUpdateRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RisksUpdateRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    RisksUpdateRiskResponse,
    RisksUpdateRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Delete Risk
 */
export const risksDeleteRisk = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RisksDeleteRiskData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    RisksDeleteRiskResponse,
    RisksDeleteRiskError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/risks/{risk_id}",
  });
};

/**
 * Create Business Process
 */
export const businessProcessesCreateBusinessProcess = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    BusinessProcessesCreateBusinessProcessData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    BusinessProcessesCreateBusinessProcessResponse,
    BusinessProcessesCreateBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes",
  });
};

/**
 * Read Business Processes
 */
export const businessProcessesReadBusinessProcesses = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<
    BusinessProcessesReadBusinessProcessesData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    BusinessProcessesReadBusinessProcessesResponse,
    BusinessProcessesReadBusinessProcessesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes",
  });
};

/**
 * Read Business Process
 */
export const businessProcessesReadBusinessProcess = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    BusinessProcessesReadBusinessProcessData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    BusinessProcessesReadBusinessProcessResponse,
    BusinessProcessesReadBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Update Business Process
 */
export const businessProcessesUpdateBusinessProcess = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    BusinessProcessesUpdateBusinessProcessData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    BusinessProcessesUpdateBusinessProcessResponse,
    BusinessProcessesUpdateBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Delete Business Process
 */
export const businessProcessesDeleteBusinessProcess = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    BusinessProcessesDeleteBusinessProcessData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    BusinessProcessesDeleteBusinessProcessResponse,
    BusinessProcessesDeleteBusinessProcessError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/business-processes/{process_id}",
  });
};

/**
 * Create Regulatory Framework
 */
export const regulatoryFrameworksCreateRegulatoryFramework = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryFrameworksCreateRegulatoryFrameworkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    RegulatoryFrameworksCreateRegulatoryFrameworkResponse,
    RegulatoryFrameworksCreateRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks",
  });
};

/**
 * Read Regulatory Frameworks
 */
export const regulatoryFrameworksReadRegulatoryFrameworks = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<
    RegulatoryFrameworksReadRegulatoryFrameworksData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    RegulatoryFrameworksReadRegulatoryFrameworksResponse,
    RegulatoryFrameworksReadRegulatoryFrameworksError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks",
  });
};

/**
 * Read Regulatory Framework
 */
export const regulatoryFrameworksReadRegulatoryFramework = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryFrameworksReadRegulatoryFrameworkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    RegulatoryFrameworksReadRegulatoryFrameworkResponse,
    RegulatoryFrameworksReadRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Update Regulatory Framework
 */
export const regulatoryFrameworksUpdateRegulatoryFramework = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryFrameworksUpdateRegulatoryFrameworkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    RegulatoryFrameworksUpdateRegulatoryFrameworkResponse,
    RegulatoryFrameworksUpdateRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Delete Regulatory Framework
 */
export const regulatoryFrameworksDeleteRegulatoryFramework = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryFrameworksDeleteRegulatoryFrameworkData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    RegulatoryFrameworksDeleteRegulatoryFrameworkResponse,
    RegulatoryFrameworksDeleteRegulatoryFrameworkError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-frameworks/{framework_id}",
  });
};

/**
 * Create Regulatory Requirement
 */
export const regulatoryRequirementsCreateRegulatoryRequirement = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryRequirementsCreateRegulatoryRequirementData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    RegulatoryRequirementsCreateRegulatoryRequirementResponse,
    RegulatoryRequirementsCreateRegulatoryRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-requirements",
  });
};

/**
 * Read Regulatory Requirements
 */
export const regulatoryRequirementsReadRegulatoryRequirements = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<
    RegulatoryRequirementsReadRegulatoryRequirementsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    RegulatoryRequirementsReadRegulatoryRequirementsResponse,
    RegulatoryRequirementsReadRegulatoryRequirementsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-requirements",
  });
};

/**
 * Read Regulatory Requirement
 */
export const regulatoryRequirementsReadRegulatoryRequirement = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryRequirementsReadRegulatoryRequirementData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    RegulatoryRequirementsReadRegulatoryRequirementResponse,
    RegulatoryRequirementsReadRegulatoryRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-requirements/{requirement_id}",
  });
};

/**
 * Update Regulatory Requirement
 */
export const regulatoryRequirementsUpdateRegulatoryRequirement = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryRequirementsUpdateRegulatoryRequirementData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    RegulatoryRequirementsUpdateRegulatoryRequirementResponse,
    RegulatoryRequirementsUpdateRegulatoryRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-requirements/{requirement_id}",
  });
};

/**
 * Delete Regulatory Requirement
 */
export const regulatoryRequirementsDeleteRegulatoryRequirement = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RegulatoryRequirementsDeleteRegulatoryRequirementData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    RegulatoryRequirementsDeleteRegulatoryRequirementResponse,
    RegulatoryRequirementsDeleteRegulatoryRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/regulatory-requirements/{requirement_id}",
  });
};

/**
 * Create User
 * Create a new user.
 * Requires admin role.
 * The new user is assigned to the admin's tenant.
 */
export const usersCreateUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersCreateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UsersCreateUserResponse,
    UsersCreateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users",
  });
};

/**
 * List Users
 * List users in the current tenant, optionally filtered by role.
 * Requires admin or compliance_officer role.
 */
export const usersListUsers = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<UsersListUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersListUsersResponse,
    UsersListUsersError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users",
  });
};

/**
 * Get Current User
 * Get the current authenticated user's information including their role.
 */
export const usersGetCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersGetCurrentUserResponse,
    UsersGetCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update User Role
 */
export const usersUpdateUserRole = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUpdateUserRoleData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UsersUpdateUserRoleResponse,
    UsersUpdateUserRoleError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{user_id}/role",
  });
};

/**
 * Upload Document
 * Upload a regulatory document for AI analysis.
 */
export const documentsUploadDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DocumentsUploadDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    DocumentsUploadDocumentResponse,
    DocumentsUploadDocumentError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/documents/upload",
  });
};

/**
 * List Documents
 * List all documents for the current user's tenant.
 */
export const documentsListDocuments = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    DocumentsListDocumentsResponse,
    DocumentsListDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents",
  });
};

/**
 * Get Document
 * Get a specific document by ID.
 *
 * - Requires admin, bpo, or executive role
 * - Returns document metadata
 */
export const documentsGetDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DocumentsGetDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    DocumentsGetDocumentResponse,
    DocumentsGetDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}",
  });
};

/**
 * Delete Document
 * Archive a document (soft delete).
 *
 * - **document_id**: UUID of the document to archive
 * - Requires admin role
 * - Moves document to archive in both database and Supabase storage
 * - Returns success message
 */
export const documentsDeleteDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DocumentsDeleteDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DocumentsDeleteDocumentResponse,
    DocumentsDeleteDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}",
  });
};

/**
 * Rename Document
 * Rename a document.
 *
 * - **document_id**: UUID of the document to rename
 * - **new_filename**: New filename for the document (in request body)
 * - Requires admin role
 * - Updates filename in database only (storage path remains unchanged)
 * - File extension is preserved automatically
 * - Returns updated document metadata
 */
export const documentsRenameDocument = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DocumentsRenameDocumentData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    DocumentsRenameDocumentResponse,
    DocumentsRenameDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/rename",
  });
};

/**
 * Manually Process Document
 * Manually trigger document processing (for testing/debugging).
 *
 * - **document_id**: UUID of the document to process
 * - Requires admin role
 * - Processes document synchronously and returns detailed status
 * - Useful for debugging when automatic processing fails
 */
export const documentsManuallyProcessDocument = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    DocumentsManuallyProcessDocumentData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    DocumentsManuallyProcessDocumentResponse,
    DocumentsManuallyProcessDocumentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/process",
  });
};

/**
 * List Suggestions
 * List AI suggestions with optional status filtering.
 * Filtered by tenant - only shows suggestions from documents uploaded by users in the same tenant.
 */
export const suggestionsListSuggestions = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<SuggestionsListSuggestionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SuggestionsListSuggestionsResponse,
    SuggestionsListSuggestionsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/suggestions",
  });
};

/**
 * Update Suggestion Status
 * Update the status of an AI suggestion.
 * Transitions:
 * - pending -> awaiting_bpo_approval (Accept)
 * - pending -> rejected (Reject)
 */
export const suggestionsUpdateSuggestionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SuggestionsUpdateSuggestionStatusData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).patch<
    SuggestionsUpdateSuggestionStatusResponse,
    SuggestionsUpdateSuggestionStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/suggestions/{suggestion_id}/status",
  });
};

/**
 * List Audit Logs
 * Retrieve audit logs.
 * Requires admin or compliance_officer role.
 */
export const auditLogsListAuditLogs = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<AuditLogsListAuditLogsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuditLogsListAuditLogsResponse,
    AuditLogsListAuditLogsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/audit-logs",
  });
};

/**
 * Get Dashboard Metrics
 * Retrieve role-specific dashboard metrics for the authenticated user.
 *
 * Returns:
 * DashboardMetrics: Role-specific dashboard cards and data
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (user inactive or invalid tenant)
 * 500: Internal server error (database/service failure)
 */
export const dashboardGetDashboardMetrics = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    DashboardGetDashboardMetricsResponse,
    DashboardGetDashboardMetricsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/dashboard/metrics",
  });
};

/**
 * Get Pending Reviews
 * Retrieve paginated list of suggestions with status 'pending_review' assigned to the logged-in BPO.
 *
 * Only accessible to users with BPO role. Returns suggestions filtered by:
 * - status = "pending_review"
 * - assigned_bpo_id = current_user.id
 * - tenant_id = current_user.tenant_id (enforced by RLS)
 *
 * Args:
 * page: Page number (1-indexed)
 * size: Number of items per page (max 100)
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * PendingReviewsResponse: Paginated list of pending review items
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-BPO user or user has no tenant)
 * 500: Internal server error
 */
export const assessmentsGetPendingReviews = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<AssessmentsGetPendingReviewsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AssessmentsGetPendingReviewsResponse,
    AssessmentsGetPendingReviewsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/pending",
  });
};

/**
 * Get Suggestion Detail
 * Retrieve detailed information for a specific AI suggestion.
 *
 * Only accessible to BPO assigned to the suggestion.
 *
 * Args:
 * suggestion_id: ID of the suggestion
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * SuggestionDetailResponse: Detailed suggestion data
 *
 * Raises:
 * 403: Forbidden (not BPO or not assigned)
 * 404: Not Found
 */
export const assessmentsGetSuggestionDetail = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    AssessmentsGetSuggestionDetailData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    AssessmentsGetSuggestionDetailResponse,
    AssessmentsGetSuggestionDetailError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/{suggestion_id}",
  });
};

/**
 * Submit Assessment
 * Submit BPO assessment action (approve or discard) for an AI suggestion.
 *
 * Authorization checks:
 * - User must have BPO role
 * - Suggestion.assigned_bpo_id must match current_user.id
 * - Suggestion.tenant_id must match current_user.tenant_id (enforced by service layer)
 *
 * Validation:
 * - For approve action: residual_risk is REQUIRED (400 Bad Request if missing)
 * - Suggestion must exist and have status "pending_review" (404 if not found, 409 if wrong status)
 *
 * Side effects:
 * - Approve: Creates active records (business_process, risk, control), updates status to "active"
 * - Discard: Updates status to "archived"
 * - Both actions: Creates immutable audit log entry
 *
 * Args:
 * suggestion_id: ID of the suggestion to assess
 * request: AssessmentRequest with action, residual_risk (if approve), and optional edits
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * AssessmentResponse: Success status, message, updated status, audit_log_id, and active_record_ids (if approved)
 *
 * Raises:
 * 400: Bad Request (residual_risk missing for approve action)
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-BPO user, not assigned to this suggestion, or no tenant)
 * 404: Not Found (suggestion doesn't exist or belongs to different tenant)
 * 409: Conflict (suggestion status is not "pending_review")
 * 500: Internal server error
 */
export const assessmentsSubmitAssessment = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<AssessmentsSubmitAssessmentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AssessmentsSubmitAssessmentResponse,
    AssessmentsSubmitAssessmentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/assessments/{suggestion_id}/assess",
  });
};

/**
 * Create Mapping
 * Create a new control-to-requirement mapping.
 *
 * Only accessible to Admin users. Validates that both control and requirement
 * exist in the user's tenant, prevents duplicate mappings, and logs the action
 * to the audit trail.
 *
 * Args:
 * payload: MappingCreate with control_id and regulatory_requirement_id
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingDetail: Created mapping with control and requirement names
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin user)
 * 400: Bad Request (invalid control_id or requirement_id)
 * 409: Conflict (mapping already exists)
 */
export const mappingsCreateMapping = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<MappingsCreateMappingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    MappingsCreateMappingResponse,
    MappingsCreateMappingError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings",
  });
};

/**
 * Delete Mapping
 * Delete a control-to-requirement mapping.
 *
 * Only accessible to Admin users. Idempotent operation - returns 404 if
 * mapping doesn't exist. Logs the deletion to the audit trail.
 *
 * Args:
 * payload: MappingDelete with control_id and regulatory_requirement_id
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin user)
 * 404: Not Found (mapping doesn't exist)
 */
export const mappingsDeleteMapping = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<MappingsDeleteMappingData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    MappingsDeleteMappingResponse,
    MappingsDeleteMappingError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings",
  });
};

/**
 * Get Mappings For Control
 * Get all regulatory requirements mapped to a specific control.
 *
 * Accessible to Admin, Executive, and BPO users. Returns list of mappings
 * with requirement names for display.
 *
 * Args:
 * control_id: UUID of the control
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingListResponse: List of mappings with total count
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin/Executive/BPO user)
 * 404: Not Found (control doesn't exist or not in user's tenant)
 */
export const mappingsGetMappingsForControl = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<MappingsGetMappingsForControlData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    MappingsGetMappingsForControlResponse,
    MappingsGetMappingsForControlError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings/control/{control_id}",
  });
};

/**
 * Get Mappings For Requirement
 * Get all controls mapped to a specific regulatory requirement.
 *
 * Accessible to Admin, Executive, and BPO users. Returns list of mappings
 * with control names for display.
 *
 * Args:
 * requirement_id: UUID of the regulatory requirement
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * MappingListResponse: List of mappings with total count
 *
 * Raises:
 * 401: Unauthorized (JWT missing/invalid)
 * 403: Forbidden (non-Admin/Executive/BPO user)
 * 404: Not Found (requirement doesn't exist or not in user's tenant)
 */
export const mappingsGetMappingsForRequirement = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    MappingsGetMappingsForRequirementData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    MappingsGetMappingsForRequirementResponse,
    MappingsGetMappingsForRequirementError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/mappings/requirement/{requirement_id}",
  });
};

/**
 * Generate Gap Analysis Report
 * Generate a gap analysis report for a selected regulatory framework.
 *
 * Identifies regulatory requirements with no associated controls.
 * Accessible to Admin and Executive roles.
 *
 * Args:
 * framework_id: UUID of the regulatory framework
 * db: Database session
 * current_user: Authenticated user from JWT
 *
 * Returns:
 * GapAnalysisReport: Structured report
 *
 * Raises:
 * 401: Unauthorized
 * 403: Forbidden (non-Admin/Executive)
 * 404: Not Found (framework doesn't exist)
 */
export const reportsGenerateGapAnalysisReport = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ReportsGenerateGapAnalysisReportData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ReportsGenerateGapAnalysisReportResponse,
    ReportsGenerateGapAnalysisReportError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/reports/gap-analysis/{framework_id}",
  });
};
