// This file is auto-generated by @hey-api/openapi-ts

export type AISuggestionRead = {
  type: SuggestionType;
  content: {
    [key: string]: unknown;
  };
  rationale: string;
  source_reference: string;
  id: string;
  status: SuggestionStatus;
  document_id: string;
};

/**
 * Actions available to BPO when assessing AI suggestions.
 */
export type AssessmentAction = "approve" | "discard";

/**
 * Request payload for BPO assessment action.
 *
 * When approving, residual_risk is mandatory. When editing before approval,
 * edited field values override the original AI-suggested values.
 */
export type AssessmentRequest = {
  /**
   * Assessment action: approve or discard
   */
  action: AssessmentAction;
  /**
   * Required for 'approve' action. Categorizes residual risk level.
   */
  residual_risk?: ResidualRisk | null;
  /**
   * Edited risk description (overrides AI suggestion if provided)
   */
  edited_risk_description?: string | null;
  /**
   * Edited control description (overrides AI suggestion if provided)
   */
  edited_control_description?: string | null;
  /**
   * Edited business process name (overrides AI suggestion if provided)
   */
  edited_business_process?: string | null;
};

/**
 * Response after BPO assessment action.
 *
 * Returns success status, updated suggestion status, and audit log reference
 * for traceability.
 */
export type AssessmentResponse = {
  /**
   * Whether the assessment action succeeded
   */
  success: boolean;
  /**
   * Human-readable success or error message
   */
  message: string;
  /**
   * Updated suggestion status: 'active' (approved) or 'archived' (discarded)
   */
  updated_status: string;
  /**
   * Reference to audit log entry for this action
   */
  audit_log_id: string;
  /**
   * IDs of created active records (business_process_id, risk_id, control_id) if approved
   */
  active_record_ids?: {
    [key: string]: string;
  } | null;
};

export type AuditLogRead = {
  action: string;
  entity_type: string;
  entity_id: string;
  changes?: {
    [key: string]: unknown;
  } | null;
  id: string;
  actor_id: string;
  created_at: string;
};

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type Body_documents_upload_document = {
  file: Blob | File;
};

export type BusinessProcessCreate = {
  name: string;
  description?: string | null;
};

export type BusinessProcessRead = {
  name: string;
  description?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type BusinessProcessUpdate = {
  name: string;
  description?: string | null;
};

export type ControlCreate = {
  name: string;
  description?: string | null;
  type?: string | null;
};

export type ControlRead = {
  name: string;
  description?: string | null;
  type?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type ControlUpdate = {
  name: string;
  description?: string | null;
  type?: string | null;
};

/**
 * Single card data for Action-Oriented Hub dashboard.
 *
 * Represents a modular dashboard card displaying a key metric
 * with an actionable link for the user to drill down.
 */
export type DashboardCard = {
  /**
   * Unique identifier for the card type
   */
  card_id: string;
  /**
   * Display title for the card
   */
  title: string;
  /**
   * Primary numeric metric to display
   */
  metric: number;
  /**
   * Label for the metric (e.g., 'items', 'risks')
   */
  metric_label: string;
  /**
   * Icon identifier for frontend rendering
   */
  icon: string;
  /**
   * URL for the card's CTA button
   */
  action_link: string;
  /**
   * Optional status indicator (e.g., 'urgent', 'normal')
   */
  status?: string | null;
};

/**
 * Complete dashboard data feed for a specific user role.
 *
 * Contains all cards that should be displayed on the user's
 * personalized Action-Oriented Hub dashboard.
 */
export type DashboardMetrics = {
  /**
   * User's role (admin, bpo, executive, general)
   */
  user_role: string;
  /**
   * List of dashboard cards for this role
   */
  cards: Array<DashboardCard>;
};

/**
 * Schema for reading a document.
 */
export type DocumentRead = {
  filename: string;
  id: string;
  storage_path: string;
  status: DocumentStatus;
  uploaded_by: string;
  created_at: string;
};

/**
 * Status of document processing.
 */
export type DocumentStatus = "pending" | "processing" | "completed" | "failed";

/**
 * Response after successful upload.
 */
export type DocumentUploadResponse = {
  id: string;
  filename: string;
  status: DocumentStatus;
  message?: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Page_BusinessProcessRead_ = {
  items: Array<BusinessProcessRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_ControlRead_ = {
  items: Array<ControlRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_ItemRead_ = {
  items: Array<ItemRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_RegulatoryFrameworkRead_ = {
  items: Array<RegulatoryFrameworkRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_RiskRead_ = {
  items: Array<RiskRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

/**
 * Single pending review item for BPO pending reviews list.
 *
 * Displays key information about an AI suggestion awaiting BPO approval.
 */
export type PendingReviewItem = {
  /**
   * Unique identifier for the suggestion
   */
  suggestion_id: string;
  /**
   * AI-suggested business process name
   */
  business_process_name: string;
  /**
   * AI-suggested risk name
   */
  risk_name: string;
  /**
   * AI-suggested control name
   */
  control_name: string;
  /**
   * Link to original document clause
   */
  source_reference: string;
  /**
   * ISO 8601 timestamp when suggestion was created
   */
  created_at: string;
};

/**
 * Paginated response for BPO pending reviews list.
 */
export type PendingReviewsResponse = {
  /**
   * List of pending review items for current page
   */
  items: Array<PendingReviewItem>;
  /**
   * Total number of pending reviews for this BPO
   */
  total: number;
  /**
   * Current page number (1-indexed)
   */
  page: number;
  /**
   * Page size
   */
  size: number;
};

export type RegulatoryFrameworkCreate = {
  name: string;
  description?: string | null;
  version?: string | null;
};

export type RegulatoryFrameworkRead = {
  name: string;
  description?: string | null;
  version?: string | null;
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
};

export type RegulatoryFrameworkUpdate = {
  name: string;
  description?: string | null;
  version?: string | null;
};

export type RenameRequest = {
  new_filename: string;
};

/**
 * Residual risk categorization levels for approved controls.
 */
export type ResidualRisk = "low" | "medium" | "high";

export type RiskCreate = {
  name: string;
  description?: string | null;
  category?: string | null;
};

export type RiskRead = {
  name: string;
  description?: string | null;
  category?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type RiskUpdate = {
  name: string;
  description?: string | null;
  category?: string | null;
};

/**
 * Detailed view of an AI suggestion for BPO assessment.
 *
 * Includes full descriptions and rationale needed for decision making.
 */
export type SuggestionDetailResponse = {
  /**
   * Unique identifier for the suggestion
   */
  suggestion_id: string;
  /**
   * AI-suggested business process name
   */
  business_process_name: string;
  /**
   * AI-suggested risk name
   */
  risk_name: string;
  /**
   * AI-suggested risk description
   */
  risk_description: string;
  /**
   * AI-suggested control name
   */
  control_name: string;
  /**
   * AI-suggested control description
   */
  control_description: string;
  /**
   * AI's reasoning for this suggestion
   */
  rationale: string;
  /**
   * Link to original document clause
   */
  source_reference: string;
  /**
   * ISO 8601 timestamp when suggestion was created
   */
  created_at: string;
};

export type SuggestionStatus =
  | "pending"
  | "pending_review"
  | "active"
  | "archived"
  | "rejected";

export type SuggestionType = "risk" | "control";

export type UpdateSuggestionStatusRequest = {
  status: SuggestionStatus;
  updated_content?: {
    [key: string]: unknown;
  } | null;
  bpo_id?: string | null;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  role?: string;
  tenant_id?: string | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  role: string;
  tenant_id: string;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  role?: string | null;
  tenant_id?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthAuthJwtLoginData = {
  body: login;
};

export type AuthAuthJwtLoginResponse = BearerResponse;

export type AuthAuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthAuthJwtLogoutResponse = unknown;

export type AuthAuthJwtLogoutError = unknown;

export type AuthRegisterRegisterData = {
  body: UserCreate;
};

export type AuthRegisterRegisterResponse = UserRead;

export type AuthRegisterRegisterError = ErrorModel | HTTPValidationError;

export type AuthResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type AuthResetForgotPasswordResponse = unknown;

export type AuthResetForgotPasswordError = HTTPValidationError;

export type AuthResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type AuthResetResetPasswordResponse = unknown;

export type AuthResetResetPasswordError = ErrorModel | HTTPValidationError;

export type AuthVerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type AuthVerifyRequestTokenResponse = unknown;

export type AuthVerifyRequestTokenError = HTTPValidationError;

export type AuthVerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type AuthVerifyVerifyResponse = UserRead;

export type AuthVerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersUsersCurrentUserResponse = UserRead;

export type UsersUsersCurrentUserError = unknown;

export type UsersUsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersUsersPatchCurrentUserResponse = UserRead;

export type UsersUsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUsersUserResponse = UserRead;

export type UsersUsersUserError = unknown | HTTPValidationError;

export type UsersUsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersUsersPatchUserResponse = UserRead;

export type UsersUsersPatchUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersUsersDeleteUserResponse = void;

export type UsersUsersDeleteUserError = unknown | HTTPValidationError;

export type ItemReadItemData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ItemReadItemResponse = Page_ItemRead_;

export type ItemReadItemError = HTTPValidationError;

export type ItemCreateItemData = {
  body: ItemCreate;
};

export type ItemCreateItemResponse = ItemRead;

export type ItemCreateItemError = HTTPValidationError;

export type ItemDeleteItemData = {
  path: {
    item_id: string;
  };
};

export type ItemDeleteItemResponse = unknown;

export type ItemDeleteItemError = HTTPValidationError;

export type ControlsCreateControlData = {
  body: ControlCreate;
};

export type ControlsCreateControlResponse = ControlRead;

export type ControlsCreateControlError = HTTPValidationError;

export type ControlsReadControlsData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ControlsReadControlsResponse = Page_ControlRead_;

export type ControlsReadControlsError = HTTPValidationError;

export type ControlsReadControlData = {
  path: {
    control_id: string;
  };
};

export type ControlsReadControlResponse = ControlRead;

export type ControlsReadControlError = HTTPValidationError;

export type ControlsUpdateControlData = {
  body: ControlUpdate;
  path: {
    control_id: string;
  };
};

export type ControlsUpdateControlResponse = ControlRead;

export type ControlsUpdateControlError = HTTPValidationError;

export type ControlsDeleteControlData = {
  path: {
    control_id: string;
  };
};

export type ControlsDeleteControlResponse = void;

export type ControlsDeleteControlError = HTTPValidationError;

export type RisksCreateRiskData = {
  body: RiskCreate;
};

export type RisksCreateRiskResponse = RiskRead;

export type RisksCreateRiskError = HTTPValidationError;

export type RisksReadRisksData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type RisksReadRisksResponse = Page_RiskRead_;

export type RisksReadRisksError = HTTPValidationError;

export type RisksReadRiskData = {
  path: {
    risk_id: string;
  };
};

export type RisksReadRiskResponse = RiskRead;

export type RisksReadRiskError = HTTPValidationError;

export type RisksUpdateRiskData = {
  body: RiskUpdate;
  path: {
    risk_id: string;
  };
};

export type RisksUpdateRiskResponse = RiskRead;

export type RisksUpdateRiskError = HTTPValidationError;

export type RisksDeleteRiskData = {
  path: {
    risk_id: string;
  };
};

export type RisksDeleteRiskResponse = void;

export type RisksDeleteRiskError = HTTPValidationError;

export type BusinessProcessesCreateBusinessProcessData = {
  body: BusinessProcessCreate;
};

export type BusinessProcessesCreateBusinessProcessResponse =
  BusinessProcessRead;

export type BusinessProcessesCreateBusinessProcessError = HTTPValidationError;

export type BusinessProcessesReadBusinessProcessesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type BusinessProcessesReadBusinessProcessesResponse =
  Page_BusinessProcessRead_;

export type BusinessProcessesReadBusinessProcessesError = HTTPValidationError;

export type BusinessProcessesReadBusinessProcessData = {
  path: {
    process_id: string;
  };
};

export type BusinessProcessesReadBusinessProcessResponse = BusinessProcessRead;

export type BusinessProcessesReadBusinessProcessError = HTTPValidationError;

export type BusinessProcessesUpdateBusinessProcessData = {
  body: BusinessProcessUpdate;
  path: {
    process_id: string;
  };
};

export type BusinessProcessesUpdateBusinessProcessResponse =
  BusinessProcessRead;

export type BusinessProcessesUpdateBusinessProcessError = HTTPValidationError;

export type BusinessProcessesDeleteBusinessProcessData = {
  path: {
    process_id: string;
  };
};

export type BusinessProcessesDeleteBusinessProcessResponse = void;

export type BusinessProcessesDeleteBusinessProcessError = HTTPValidationError;

export type RegulatoryFrameworksCreateRegulatoryFrameworkData = {
  body: RegulatoryFrameworkCreate;
};

export type RegulatoryFrameworksCreateRegulatoryFrameworkResponse =
  RegulatoryFrameworkRead;

export type RegulatoryFrameworksCreateRegulatoryFrameworkError =
  HTTPValidationError;

export type RegulatoryFrameworksReadRegulatoryFrameworksData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type RegulatoryFrameworksReadRegulatoryFrameworksResponse =
  Page_RegulatoryFrameworkRead_;

export type RegulatoryFrameworksReadRegulatoryFrameworksError =
  HTTPValidationError;

export type RegulatoryFrameworksReadRegulatoryFrameworkData = {
  path: {
    framework_id: string;
  };
};

export type RegulatoryFrameworksReadRegulatoryFrameworkResponse =
  RegulatoryFrameworkRead;

export type RegulatoryFrameworksReadRegulatoryFrameworkError =
  HTTPValidationError;

export type RegulatoryFrameworksUpdateRegulatoryFrameworkData = {
  body: RegulatoryFrameworkUpdate;
  path: {
    framework_id: string;
  };
};

export type RegulatoryFrameworksUpdateRegulatoryFrameworkResponse =
  RegulatoryFrameworkRead;

export type RegulatoryFrameworksUpdateRegulatoryFrameworkError =
  HTTPValidationError;

export type RegulatoryFrameworksDeleteRegulatoryFrameworkData = {
  path: {
    framework_id: string;
  };
};

export type RegulatoryFrameworksDeleteRegulatoryFrameworkResponse = void;

export type RegulatoryFrameworksDeleteRegulatoryFrameworkError =
  HTTPValidationError;

export type UsersGetCurrentUserResponse = UserRead;

export type UsersGetCurrentUserError = unknown;

export type UsersListUsersData = {
  query?: {
    role?: string | null;
  };
};

export type UsersListUsersResponse = Array<UserRead>;

export type UsersListUsersError = HTTPValidationError;

export type UsersUpdateUserRoleData = {
  body: UserUpdate;
  path: {
    user_id: string;
  };
};

export type UsersUpdateUserRoleResponse = UserRead;

export type UsersUpdateUserRoleError = HTTPValidationError;

export type DocumentsUploadDocumentData = {
  body: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = DocumentUploadResponse;

export type DocumentsUploadDocumentError = HTTPValidationError;

export type DocumentsListDocumentsResponse = Array<DocumentRead>;

export type DocumentsListDocumentsError = unknown;

export type DocumentsGetDocumentData = {
  path: {
    document_id: string;
  };
};

export type DocumentsGetDocumentResponse = DocumentRead;

export type DocumentsGetDocumentError = HTTPValidationError;

export type DocumentsDeleteDocumentData = {
  path: {
    document_id: string;
  };
};

export type DocumentsDeleteDocumentResponse = unknown;

export type DocumentsDeleteDocumentError = HTTPValidationError;

export type DocumentsRenameDocumentData = {
  body: RenameRequest;
  path: {
    document_id: string;
  };
};

export type DocumentsRenameDocumentResponse = DocumentRead;

export type DocumentsRenameDocumentError = HTTPValidationError;

export type DocumentsManuallyProcessDocumentData = {
  path: {
    document_id: string;
  };
};

export type DocumentsManuallyProcessDocumentResponse = unknown;

export type DocumentsManuallyProcessDocumentError = HTTPValidationError;

export type SuggestionsListSuggestionsData = {
  query?: {
    /**
     * Filter by status
     */
    status?: SuggestionStatus | null;
  };
};

export type SuggestionsListSuggestionsResponse = Array<AISuggestionRead>;

export type SuggestionsListSuggestionsError = HTTPValidationError;

export type SuggestionsUpdateSuggestionStatusData = {
  body: UpdateSuggestionStatusRequest;
  path: {
    suggestion_id: string;
  };
};

export type SuggestionsUpdateSuggestionStatusResponse = AISuggestionRead;

export type SuggestionsUpdateSuggestionStatusError = HTTPValidationError;

export type AuditLogsListAuditLogsData = {
  query?: {
    /**
     * Filter by actor ID
     */
    actor_id?: string | null;
    /**
     * Filter by entity ID
     */
    entity_id?: string | null;
    /**
     * Filter by entity type
     */
    entity_type?: string | null;
  };
};

export type AuditLogsListAuditLogsResponse = Array<AuditLogRead>;

export type AuditLogsListAuditLogsError = HTTPValidationError;

export type DashboardGetDashboardMetricsResponse = DashboardMetrics;

export type DashboardGetDashboardMetricsError = unknown;

export type AssessmentsGetPendingReviewsData = {
  query?: {
    /**
     * Page number (1-indexed)
     */
    page?: number;
    /**
     * Page size (max 100)
     */
    size?: number;
  };
};

export type AssessmentsGetPendingReviewsResponse = PendingReviewsResponse;

export type AssessmentsGetPendingReviewsError = HTTPValidationError;

export type AssessmentsGetSuggestionDetailData = {
  path: {
    /**
     * ID of the suggestion to retrieve
     */
    suggestion_id: string;
  };
};

export type AssessmentsGetSuggestionDetailResponse = SuggestionDetailResponse;

export type AssessmentsGetSuggestionDetailError = HTTPValidationError;

export type AssessmentsSubmitAssessmentData = {
  body: AssessmentRequest;
  path: {
    /**
     * ID of the suggestion to assess
     */
    suggestion_id: string;
  };
};

export type AssessmentsSubmitAssessmentResponse = AssessmentResponse;

export type AssessmentsSubmitAssessmentError = HTTPValidationError;
