// This file is auto-generated by @hey-api/openapi-ts

export type AISuggestionRead = {
  type: SuggestionType;
  content: {
    [key: string]: unknown;
  };
  rationale: string;
  source_reference: string;
  id: string;
  status: SuggestionStatus;
  document_id: string;
};

/**
 * Actions available to BPO when assessing AI suggestions.
 */
export type AssessmentAction = "approve" | "discard";

/**
 * Request payload for BPO assessment action.
 *
 * When approving, residual_risk is mandatory. When editing before approval,
 * edited field values override the original AI-suggested values.
 */
export type AssessmentRequest = {
  /**
   * Assessment action: approve or discard
   */
  action: AssessmentAction;
  /**
   * Required for 'approve' action. Categorizes residual risk level.
   */
  residual_risk?: ResidualRisk | null;
  /**
   * Edited risk description (overrides AI suggestion if provided)
   */
  edited_risk_description?: string | null;
  /**
   * Edited control description (overrides AI suggestion if provided)
   */
  edited_control_description?: string | null;
  /**
   * Edited business process name (overrides AI suggestion if provided)
   */
  edited_business_process?: string | null;
};

/**
 * Response after BPO assessment action.
 *
 * Returns success status, updated suggestion status, and audit log reference
 * for traceability.
 */
export type AssessmentResponse = {
  /**
   * Whether the assessment action succeeded
   */
  success: boolean;
  /**
   * Human-readable success or error message
   */
  message: string;
  /**
   * Updated suggestion status: 'active' (approved) or 'archived' (discarded)
   */
  updated_status: string;
  /**
   * Reference to audit log entry for this action
   */
  audit_log_id: string;
  /**
   * IDs of created active records (business_process_id, risk_id, control_id) if approved
   */
  active_record_ids?: {
    [key: string]: string;
  } | null;
};

export type AuditLogRead = {
  action: string;
  entity_type: string;
  entity_id: string;
  changes?: {
    [key: string]: unknown;
  } | null;
  id: string;
  actor_id: string;
  created_at: string;
};

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type Body_documents_upload_document = {
  file: Blob | File;
};

export type BusinessProcessCreate = {
  name: string;
  description?: string | null;
};

export type BusinessProcessRead = {
  name: string;
  description?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type BusinessProcessUpdate = {
  name: string;
  description?: string | null;
};

export type ControlCreate = {
  name: string;
  description?: string | null;
  type?: string | null;
};

export type ControlRead = {
  name: string;
  description?: string | null;
  type?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type ControlUpdate = {
  name: string;
  description?: string | null;
  type?: string | null;
};

/**
 * Single card data for Action-Oriented Hub dashboard.
 *
 * Represents a modular dashboard card displaying a key metric
 * with an actionable link for the user to drill down.
 */
export type DashboardCard = {
  /**
   * Unique identifier for the card type
   */
  card_id: string;
  /**
   * Display title for the card
   */
  title: string;
  /**
   * Primary numeric metric to display
   */
  metric: number;
  /**
   * Label for the metric (e.g., 'items', 'risks')
   */
  metric_label: string;
  /**
   * Icon identifier for frontend rendering
   */
  icon: string;
  /**
   * URL for the card's CTA button
   */
  action_link: string;
  /**
   * Optional status indicator (e.g., 'urgent', 'normal')
   */
  status?: string | null;
};

/**
 * Complete dashboard data feed for a specific user role.
 *
 * Contains all cards that should be displayed on the user's
 * personalized Action-Oriented Hub dashboard.
 */
export type DashboardMetrics = {
  /**
   * User's role (admin, bpo, executive, general)
   */
  user_role: string;
  /**
   * List of dashboard cards for this role
   */
  cards: Array<DashboardCard>;
};

/**
 * Schema for reading a document.
 */
export type DocumentRead = {
  filename: string;
  id: string;
  storage_path: string;
  status: DocumentStatus;
  uploaded_by: string;
  created_at: string;
};

/**
 * Status of document processing.
 */
export type DocumentStatus = "pending" | "processing" | "completed" | "failed";

/**
 * Response after successful upload.
 */
export type DocumentUploadResponse = {
  id: string;
  filename: string;
  status: DocumentStatus;
  message?: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

/**
 * Request to create a new control-requirement mapping
 */
export type MappingCreate = {
  control_id: string;
  regulatory_requirement_id: string;
};

/**
 * Request to delete a mapping
 */
export type MappingDelete = {
  control_id: string;
  regulatory_requirement_id: string;
};

/**
 * Single mapping record
 */
export type MappingDetail = {
  id: string;
  control_id: string;
  regulatory_requirement_id: string;
  control_name: string;
  requirement_name: string;
  created_at: string;
  created_by: string;
};

/**
 * List of mappings for a control or requirement
 */
export type MappingListResponse = {
  total: number;
  mappings: Array<MappingDetail>;
};

export type Page_BusinessProcessRead_ = {
  items: Array<BusinessProcessRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_ControlRead_ = {
  items: Array<ControlRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_ItemRead_ = {
  items: Array<ItemRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_RegulatoryFrameworkRead_ = {
  items: Array<RegulatoryFrameworkRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

export type Page_RiskRead_ = {
  items: Array<RiskRead>;
  total?: number | null;
  page: number | null;
  size: number | null;
  pages?: number | null;
};

/**
 * Single pending review item for BPO pending reviews list.
 *
 * Displays key information about an AI suggestion awaiting BPO approval.
 */
export type PendingReviewItem = {
  /**
   * Unique identifier for the suggestion
   */
  suggestion_id: string;
  /**
   * AI-suggested business process name
   */
  business_process_name: string;
  /**
   * AI-suggested risk name
   */
  risk_name: string;
  /**
   * AI-suggested control name
   */
  control_name: string;
  /**
   * Link to original document clause
   */
  source_reference: string;
  /**
   * ISO 8601 timestamp when suggestion was created
   */
  created_at: string;
};

/**
 * Paginated response for BPO pending reviews list.
 */
export type PendingReviewsResponse = {
  /**
   * List of pending review items for current page
   */
  items: Array<PendingReviewItem>;
  /**
   * Total number of pending reviews for this BPO
   */
  total: number;
  /**
   * Current page number (1-indexed)
   */
  page: number;
  /**
   * Page size
   */
  size: number;
};

export type RegulatoryFrameworkCreate = {
  name: string;
  description?: string | null;
  version?: string | null;
};

export type RegulatoryFrameworkRead = {
  name: string;
  description?: string | null;
  version?: string | null;
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
};

export type RegulatoryFrameworkUpdate = {
  name: string;
  description?: string | null;
  version?: string | null;
};

export type RenameRequest = {
  new_filename: string;
};

/**
 * Residual risk categorization levels for approved controls.
 */
export type ResidualRisk = "low" | "medium" | "high";

export type RiskCreate = {
  name: string;
  description?: string | null;
  category?: string | null;
};

export type RiskRead = {
  name: string;
  description?: string | null;
  category?: string | null;
  id: string;
  tenant_id: string;
  owner_id?: string | null;
  created_at: string;
  updated_at: string;
};

export type RiskUpdate = {
  name: string;
  description?: string | null;
  category?: string | null;
};

/**
 * Detailed view of an AI suggestion for BPO assessment.
 *
 * Includes full descriptions and rationale needed for decision making.
 */
export type SuggestionDetailResponse = {
  /**
   * Unique identifier for the suggestion
   */
  suggestion_id: string;
  /**
   * AI-suggested business process name
   */
  business_process_name: string;
  /**
   * AI-suggested risk name
   */
  risk_name: string;
  /**
   * AI-suggested risk description
   */
  risk_description: string;
  /**
   * AI-suggested control name
   */
  control_name: string;
  /**
   * AI-suggested control description
   */
  control_description: string;
  /**
   * AI's reasoning for this suggestion
   */
  rationale: string;
  /**
   * Link to original document clause
   */
  source_reference: string;
  /**
   * ISO 8601 timestamp when suggestion was created
   */
  created_at: string;
};

export type SuggestionStatus =
  | "pending"
  | "pending_review"
  | "active"
  | "archived"
  | "rejected";

export type SuggestionType = "risk" | "control";

export type UpdateSuggestionStatusRequest = {
  status: SuggestionStatus;
  updated_content?: {
    [key: string]: unknown;
  } | null;
  bpo_id?: string | null;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  role?: string;
  tenant_id?: string | null;
  full_name?: string | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  role: string;
  tenant_id: string;
  full_name?: string | null;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
  role?: string | null;
  tenant_id?: string | null;
  full_name?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type ReadItemData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadItemResponse = Page_ItemRead_;

export type ReadItemError = HTTPValidationError;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type CreateControlData = {
  body: ControlCreate;
};

export type CreateControlResponse = ControlRead;

export type CreateControlError = HTTPValidationError;

export type ReadControlsData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadControlsResponse = Page_ControlRead_;

export type ReadControlsError = HTTPValidationError;

export type ReadControlData = {
  path: {
    control_id: string;
  };
};

export type ReadControlResponse = ControlRead;

export type ReadControlError = HTTPValidationError;

export type UpdateControlData = {
  body: ControlUpdate;
  path: {
    control_id: string;
  };
};

export type UpdateControlResponse = ControlRead;

export type UpdateControlError = HTTPValidationError;

export type DeleteControlData = {
  path: {
    control_id: string;
  };
};

export type DeleteControlResponse = void;

export type DeleteControlError = HTTPValidationError;

export type CreateRiskData = {
  body: RiskCreate;
};

export type CreateRiskResponse = RiskRead;

export type CreateRiskError = HTTPValidationError;

export type ReadRisksData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadRisksResponse = Page_RiskRead_;

export type ReadRisksError = HTTPValidationError;

export type ReadRiskData = {
  path: {
    risk_id: string;
  };
};

export type ReadRiskResponse = RiskRead;

export type ReadRiskError = HTTPValidationError;

export type UpdateRiskData = {
  body: RiskUpdate;
  path: {
    risk_id: string;
  };
};

export type UpdateRiskResponse = RiskRead;

export type UpdateRiskError = HTTPValidationError;

export type DeleteRiskData = {
  path: {
    risk_id: string;
  };
};

export type DeleteRiskResponse = void;

export type DeleteRiskError = HTTPValidationError;

export type CreateBusinessProcessData = {
  body: BusinessProcessCreate;
};

export type CreateBusinessProcessResponse = BusinessProcessRead;

export type CreateBusinessProcessError = HTTPValidationError;

export type ReadBusinessProcessesData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadBusinessProcessesResponse = Page_BusinessProcessRead_;

export type ReadBusinessProcessesError = HTTPValidationError;

export type ReadBusinessProcessData = {
  path: {
    process_id: string;
  };
};

export type ReadBusinessProcessResponse = BusinessProcessRead;

export type ReadBusinessProcessError = HTTPValidationError;

export type UpdateBusinessProcessData = {
  body: BusinessProcessUpdate;
  path: {
    process_id: string;
  };
};

export type UpdateBusinessProcessResponse = BusinessProcessRead;

export type UpdateBusinessProcessError = HTTPValidationError;

export type DeleteBusinessProcessData = {
  path: {
    process_id: string;
  };
};

export type DeleteBusinessProcessResponse = void;

export type DeleteBusinessProcessError = HTTPValidationError;

export type CreateRegulatoryFrameworkData = {
  body: RegulatoryFrameworkCreate;
};

export type CreateRegulatoryFrameworkResponse = RegulatoryFrameworkRead;

export type CreateRegulatoryFrameworkError = HTTPValidationError;

export type ReadRegulatoryFrameworksData = {
  query?: {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
  };
};

export type ReadRegulatoryFrameworksResponse = Page_RegulatoryFrameworkRead_;

export type ReadRegulatoryFrameworksError = HTTPValidationError;

export type ReadRegulatoryFrameworkData = {
  path: {
    framework_id: string;
  };
};

export type ReadRegulatoryFrameworkResponse = RegulatoryFrameworkRead;

export type ReadRegulatoryFrameworkError = HTTPValidationError;

export type UpdateRegulatoryFrameworkData = {
  body: RegulatoryFrameworkUpdate;
  path: {
    framework_id: string;
  };
};

export type UpdateRegulatoryFrameworkResponse = RegulatoryFrameworkRead;

export type UpdateRegulatoryFrameworkError = HTTPValidationError;

export type DeleteRegulatoryFrameworkData = {
  path: {
    framework_id: string;
  };
};

export type DeleteRegulatoryFrameworkResponse = void;

export type DeleteRegulatoryFrameworkError = HTTPValidationError;

export type CreateUserData = {
  body: UserCreate;
};

export type CreateUserResponse = UserRead;

export type CreateUserError = HTTPValidationError;

export type ListUsersData = {
  query?: {
    role?: string | null;
  };
};

export type ListUsersResponse = Array<UserRead>;

export type ListUsersError = HTTPValidationError;

export type GetCurrentUserResponse = UserRead;

export type GetCurrentUserError = unknown;

export type UpdateUserRoleData = {
  body: UserUpdate;
  path: {
    user_id: string;
  };
};

export type UpdateUserRoleResponse = UserRead;

export type UpdateUserRoleError = HTTPValidationError;

export type UploadDocumentData = {
  body: Body_documents_upload_document;
};

export type UploadDocumentResponse = DocumentUploadResponse;

export type UploadDocumentError = HTTPValidationError;

export type ListDocumentsResponse = Array<DocumentRead>;

export type ListDocumentsError = unknown;

export type GetDocumentData = {
  path: {
    document_id: string;
  };
};

export type GetDocumentResponse = DocumentRead;

export type GetDocumentError = HTTPValidationError;

export type DeleteDocumentData = {
  path: {
    document_id: string;
  };
};

export type DeleteDocumentResponse = unknown;

export type DeleteDocumentError = HTTPValidationError;

export type RenameDocumentData = {
  body: RenameRequest;
  path: {
    document_id: string;
  };
};

export type RenameDocumentResponse = DocumentRead;

export type RenameDocumentError = HTTPValidationError;

export type ManuallyProcessDocumentData = {
  path: {
    document_id: string;
  };
};

export type ManuallyProcessDocumentResponse = unknown;

export type ManuallyProcessDocumentError = HTTPValidationError;

export type ListSuggestionsData = {
  query?: {
    /**
     * Filter by status
     */
    status?: SuggestionStatus | null;
  };
};

export type ListSuggestionsResponse = Array<AISuggestionRead>;

export type ListSuggestionsError = HTTPValidationError;

export type UpdateSuggestionStatusData = {
  body: UpdateSuggestionStatusRequest;
  path: {
    suggestion_id: string;
  };
};

export type UpdateSuggestionStatusResponse = AISuggestionRead;

export type UpdateSuggestionStatusError = HTTPValidationError;

export type ListAuditLogsData = {
  query?: {
    /**
     * Filter by actor ID
     */
    actor_id?: string | null;
    /**
     * Filter by entity ID
     */
    entity_id?: string | null;
    /**
     * Filter by entity type
     */
    entity_type?: string | null;
  };
};

export type ListAuditLogsResponse = Array<AuditLogRead>;

export type ListAuditLogsError = HTTPValidationError;

export type GetDashboardMetricsResponse = DashboardMetrics;

export type GetDashboardMetricsError = unknown;

export type GetPendingReviewsData = {
  query?: {
    /**
     * Page number (1-indexed)
     */
    page?: number;
    /**
     * Page size (max 100)
     */
    size?: number;
  };
};

export type GetPendingReviewsResponse = PendingReviewsResponse;

export type GetPendingReviewsError = HTTPValidationError;

export type GetSuggestionDetailData = {
  path: {
    /**
     * ID of the suggestion to retrieve
     */
    suggestion_id: string;
  };
};

export type GetSuggestionDetailResponse = SuggestionDetailResponse;

export type GetSuggestionDetailError = HTTPValidationError;

export type SubmitAssessmentData = {
  body: AssessmentRequest;
  path: {
    /**
     * ID of the suggestion to assess
     */
    suggestion_id: string;
  };
};

export type SubmitAssessmentResponse = AssessmentResponse;

export type SubmitAssessmentError = HTTPValidationError;

export type CreateMappingData = {
  body: MappingCreate;
};

export type CreateMappingResponse = MappingDetail;

export type CreateMappingError = HTTPValidationError;

export type DeleteMappingData = {
  body: MappingDelete;
};

export type DeleteMappingResponse = void;

export type DeleteMappingError = HTTPValidationError;

export type GetMappingsForControlData = {
  path: {
    /**
     * UUID of the control
     */
    control_id: string;
  };
};

export type GetMappingsForControlResponse = MappingListResponse;

export type GetMappingsForControlError = HTTPValidationError;

export type GetMappingsForRequirementData = {
  path: {
    /**
     * UUID of the regulatory requirement
     */
    requirement_id: string;
  };
};

export type GetMappingsForRequirementResponse = MappingListResponse;

export type GetMappingsForRequirementError = HTTPValidationError;
