"""Create core compliance tables

Revision ID: a8c234ea5923
Revises: c123456789ab
Create Date: 2025-12-02 23:23:50.020434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c234ea5923'
down_revision: Union[str, None] = 'c123456789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Detect database dialect
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'

    # Use appropriate types and defaults for database
    id_type = sa.UUID() if is_postgresql else sa.String(length=36)
    timestamp_default = sa.text('now()') if is_postgresql else sa.text('CURRENT_TIMESTAMP')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_frameworks',
    sa.Column('id', id_type, nullable=False),
    sa.Column('tenant_id', id_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_processes',
    sa.Column('id', id_type, nullable=False),
    sa.Column('tenant_id', id_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', id_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controls',
    sa.Column('id', id_type, nullable=False),
    sa.Column('tenant_id', id_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('owner_id', id_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', id_type, nullable=False),
    sa.Column('tenant_id', id_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('owner_id', id_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=timestamp_default, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Enable RLS (PostgreSQL only)
    if is_postgresql:
        op.execute("ALTER TABLE regulatory_frameworks ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE business_processes ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE controls ENABLE ROW LEVEL SECURITY")
        op.execute("ALTER TABLE risks ENABLE ROW LEVEL SECURITY")

        # Create RLS Policies
        # Policy for regulatory_frameworks
        op.execute("""
            CREATE POLICY "Tenant Access" ON regulatory_frameworks
            FOR ALL
            USING (tenant_id = auth.uid()::uuid)
            WITH CHECK (tenant_id = auth.uid()::uuid);
        """)

        # Policy for business_processes
        op.execute("""
            CREATE POLICY "Tenant Access" ON business_processes
            FOR ALL
            USING (tenant_id = auth.uid()::uuid)
            WITH CHECK (tenant_id = auth.uid()::uuid);
        """)

        # Policy for controls
        op.execute("""
            CREATE POLICY "Tenant Access" ON controls
            FOR ALL
            USING (tenant_id = auth.uid()::uuid)
            WITH CHECK (tenant_id = auth.uid()::uuid);
        """)

        # Policy for risks
        op.execute("""
            CREATE POLICY "Tenant Access" ON risks
            FOR ALL
            USING (tenant_id = auth.uid()::uuid)
            WITH CHECK (tenant_id = auth.uid()::uuid);
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Detect database dialect
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'

    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RLS Policies (PostgreSQL only)
    if is_postgresql:
        op.execute('DROP POLICY IF EXISTS "Tenant Access" ON risks')
        op.execute('DROP POLICY IF EXISTS "Tenant Access" ON controls')
        op.execute('DROP POLICY IF EXISTS "Tenant Access" ON business_processes')
        op.execute('DROP POLICY IF EXISTS "Tenant Access" ON regulatory_frameworks')

    op.drop_table('risks')
    op.drop_table('controls')
    op.drop_table('business_processes')
    op.drop_table('regulatory_frameworks')
    # ### end Alembic commands ###