"""make_compliance_owner_id_required_v3

Revision ID: ffc27ef450ae
Revises: 183380781e87
Create Date: 2025-12-14 15:21:36.467326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ffc27ef450ae'
down_revision: Union[str, None] = '183380781e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_suggestions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_ai_suggestions_status', table_name='ai_suggestions')
    op.drop_index('ix_ai_suggestions_status_document', table_name='ai_suggestions')
    op.alter_column('business_processes', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_business_processes_tenant_id', table_name='business_processes')
    op.alter_column('controls', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_controls_tenant_id', table_name='controls')
    op.drop_index('ix_controls_tenant_owner', table_name='controls')
    op.drop_index('idx_crr_control_id', table_name='controls_regulatory_requirements')
    op.drop_index('idx_crr_requirement_id', table_name='controls_regulatory_requirements')
    op.drop_index('idx_crr_tenant_id', table_name='controls_regulatory_requirements')
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_regulatory_frameworks_tenant_id', table_name='regulatory_frameworks')
    op.drop_index('ix_regulatory_requirements_framework_id', table_name='regulatory_requirements')
    op.drop_index('ix_regulatory_requirements_tenant_id', table_name='regulatory_requirements')
    op.alter_column('risks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_risks_tenant_id', table_name='risks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_risks_tenant_id', 'risks', ['tenant_id'], unique=False)
    op.alter_column('risks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_regulatory_requirements_tenant_id', 'regulatory_requirements', ['tenant_id'], unique=False)
    op.create_index('ix_regulatory_requirements_framework_id', 'regulatory_requirements', ['framework_id'], unique=False)
    op.create_index('ix_regulatory_frameworks_tenant_id', 'regulatory_frameworks', ['tenant_id'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index('idx_crr_tenant_id', 'controls_regulatory_requirements', ['tenant_id'], unique=False)
    op.create_index('idx_crr_requirement_id', 'controls_regulatory_requirements', ['regulatory_requirement_id'], unique=False)
    op.create_index('idx_crr_control_id', 'controls_regulatory_requirements', ['control_id'], unique=False)
    op.create_index('ix_controls_tenant_owner', 'controls', ['tenant_id', 'owner_id'], unique=False)
    op.create_index('ix_controls_tenant_id', 'controls', ['tenant_id'], unique=False)
    op.alter_column('controls', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_business_processes_tenant_id', 'business_processes', ['tenant_id'], unique=False)
    op.alter_column('business_processes', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_ai_suggestions_status_document', 'ai_suggestions', ['status', 'document_id'], unique=False)
    op.create_index('ix_ai_suggestions_status', 'ai_suggestions', ['status'], unique=False)
    op.alter_column('ai_suggestions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
