from typing import List, Callable
from fastapi import Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.database import get_async_session
from app.models.user import User
from app.core.security import get_current_user, UserToken


async def get_current_active_user(
    token_data: UserToken = Depends(get_current_user),
    db: AsyncSession = Depends(get_async_session),
) -> User:
    """
    Fetch the user from the database using the token's sub (user ID).
    This ensures we get the latest role and data from the database.
    """
    # The 'sub' field in Supabase JWT is the user's UUID
    user_id = token_data.sub

    result = await db.execute(select(User).filter(User.id == user_id))
    user = result.scalars().first()

    if not user:
        # JIT Provisioning: User exists in Supabase but not in local DB. Create them.
        # This handles the case where users are created via Supabase Auth (Frontend) 
        # but not yet synced to backend.
        
        # Determine roles based on email hint (for testing) or default
        roles = ["general_user"]
        # token_data.role is likely singular from Supabase, convert to list if meaningful or ignore
        if "bpo" in (token_data.email or "").lower():
            roles = ["bpo"]
        elif "admin" in (token_data.email or "").lower():
            roles = ["admin"]
            
        new_user = User(
            id=user_id,
            email=token_data.email,
            hashed_password="managed_by_supabase", # Dummy, auth handled by Supabase
            is_active=True,
            is_verified=True,
            roles=roles, # Updated to use roles array
            # role column is deprecated
            # tenant_id will be auto-generated by default value if not provided
        )
        if token_data.tenant_id:
             new_user.tenant_id = token_data.tenant_id
             
        db.add(new_user)
        await db.commit()
        await db.refresh(new_user)
        user = new_user

    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Inactive user",
        )

    return user


async def get_current_admin_user(current_user: User = Depends(get_current_active_user)) -> User:
    # Check if "admin" is present in the user's roles list
    if "admin" not in current_user.roles:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="The user doesn't have enough privileges",
        )
    return current_user


def has_role(required_roles: List[str]) -> Callable:
    async def role_checker(current_user: User = Depends(get_current_active_user)) -> User:
        # Check if the user has ANY of the required roles (intersection check)
        # current_user.roles is a list of strings
        user_roles = set(current_user.roles)
        required = set(required_roles)
        
        if not user_roles.intersection(required):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"The user doesn't have enough privileges. Required one of: {required_roles}",
            )
        return current_user

    return role_checker
