from typing import List, Callable
from fastapi import Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.database import get_async_session
from app.models.user import User
from app.core.security import get_current_user, UserToken


async def get_current_active_user(
    token_data: UserToken = Depends(get_current_user),
    db: AsyncSession = Depends(get_async_session),
) -> User:
    """
    Fetch the user from the database using the token's sub (user ID).
    This ensures we get the latest role and data from the database.
    """
    # The 'sub' field in Supabase JWT is the user's UUID
    user_id = token_data.sub

    result = await db.execute(select(User).filter(User.id == user_id))
    user = result.scalars().first()

    if not user:
        # JIT Provisioning: User exists in Supabase but not in local DB. Create them.
        # This handles the case where users are created via Supabase Auth (Frontend) 
        # but not yet synced to backend.
        
        # Determine role based on email hint (for testing) or default
        role = token_data.role or "general_user"
        if "bpo" in (token_data.email or "").lower():
            role = "bpo"
        elif "admin" in (token_data.email or "").lower():
            role = "admin"
            
        new_user = User(
            id=user_id,
            email=token_data.email,
            hashed_password="managed_by_supabase", # Dummy, auth handled by Supabase
            is_active=True,
            is_verified=True,
            role=role,
            # tenant_id will be auto-generated by default value if not provided
        )
        if token_data.tenant_id:
             new_user.tenant_id = token_data.tenant_id
             
        db.add(new_user)
        await db.commit()
        await db.refresh(new_user)
        user = new_user

    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Inactive user",
        )

    return user


async def get_current_admin_user(current_user: User = Depends(get_current_active_user)) -> User:
    if current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="The user doesn't have enough privileges",
        )
    return current_user


def has_role(roles: List[str]) -> Callable:
    async def role_checker(current_user: User = Depends(get_current_active_user)) -> User:
        if current_user.role not in roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="The user doesn't have enough privileges",
            )
        return current_user

    return role_checker
